# Generated by Django 4.0.8 on 2023-01-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchangerate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_of_day', models.DateField()),
                ('usd', models.DecimalField(decimal_places=6, max_digits=8)),
                ('cny', models.DecimalField(decimal_places=6, max_digits=8)),
                ('jpy', models.DecimalField(decimal_places=6, max_digits=8)),
                ('cad', models.DecimalField(decimal_places=6, max_digits=8)),
                ('aud', models.DecimalField(decimal_places=6, max_digits=8)),
                ('sgd', models.DecimalField(decimal_places=6, max_digits=8)),
                ('thb', models.DecimalField(decimal_places=6, max_digits=8)),
                ('myr', models.DecimalField(decimal_places=6, max_digits=8)),
                ('eur', models.DecimalField(decimal_places=6, max_digits=8)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
