# Generated by Django 4.0.8 on 2023-01-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangerate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='end_of_day',
            field=models.CharField(max_length=10),
        ),
    ]
